package Exception;

import org.testng.annotations.Test;

public class Divisionhandling {
	@Test
	public void division(){
		
		String s = null;
	
		try {
		System.out.println(s.length());
		}
		catch(NullPointerException e) {
			System.out.println("automation");
		}
		System.out.println("sssss");
		System.out.println("lllll");
		System.out.println("zzzzz");
		
			
		
	}
}

